version: '2'
services:
  web:
    env_file:
     - conf/development.env
    build: .
    image: cabot:web
    command: python manage.py runserver 0.0.0.0:5001
    ports:
     - "5001:5001"
    volumes:
     - .:/code
    links:
     - redis
     - db

  worker:
    env_file:
     - conf/development.env
    image: cabot:web
    command: python manage.py celery worker -B -A cabot --loglevel=DEBUG --concurrency=16 -Ofair
    volumes:
     - .:/code
    links:
     - redis
     - db

  redis:
    image: redis

  db:
    image: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=test

  wait:
    image: cabot:web
    command: dockerize -wait tcp://db:3306 -timeout 60s
    depends_on:
      - db
