# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-01-04 00:21
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cabotapp', '0002_auto_20181231_2227'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='fallback_officer',
            field=models.ForeignKey(blank=True, help_text=b'Fallback officer to alert if the duty officer is unavailable.', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='service',
            name='hipchat_instance',
            field=models.ForeignKey(blank=True, help_text=b'Hipchat instance to send Hipchat alerts to (can be none if Hipchat alerts disabled).', null=True, on_delete=django.db.models.deletion.SET_NULL, to='cabotapp.HipchatInstance'),
        ),
        migrations.AlterField(
            model_name='service',
            name='mattermost_instance',
            field=models.ForeignKey(blank=True, help_text=b'Mattermost instance to send alerts to (can be blank if Mattermost alerts are disabled).', null=True, on_delete=django.db.models.deletion.SET_NULL, to='cabotapp.MatterMostInstance'),
        ),
        migrations.AlterField(
            model_name='statuscheck',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
