# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-02-13 18:57
from __future__ import unicode_literals

from django.db import migrations
import timezone_field.fields


class Migration(migrations.Migration):

    dependencies = [
        ('cabotapp', '0003_auto_20190104_0021'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='timezone',
            field=timezone_field.fields.TimeZoneField(default=b'UTC'),
        ),
    ]
