# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-03-01 21:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cabotapp', '0004_userprofile_timezone'),
    ]

    operations = [
        migrations.CreateModel(
            name='StatusCheckResultTag',
            fields=[
                ('value', models.CharField(max_length=255, primary_key=True, serialize=False)),
            ],
        ),
        migrations.AddField(
            model_name='statuscheckresult',
            name='tags',
            field=models.ManyToManyField(to='cabotapp.StatusCheckResultTag'),
        ),
    ]
