# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-05-14 23:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cabotapp', '0006_acknowledgements'),
    ]

    operations = [
        migrations.AddField(
            model_name='acknowledgement',
            name='tags',
            field=models.ManyToManyField(to='cabotapp.StatusCheckResultTag'),
        ),
        migrations.AlterField(
            model_name='acknowledgement',
            name='match_if',
            field=models.TextField(choices=[(b'A', b'Result tags are in this set of tags (recommended).'), (b'C', b'Only match check, ignore tags.')], default=b'A', max_length=1),
        ),
    ]
