# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-10-11 23:12
from __future__ import unicode_literals

import cabot.cabotapp.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cabotapp', '0007_acks_with_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='statuscheck',
            name='run_window',
            field=cabot.cabotapp.fields.CheckRunWindowField(blank=True),
        ),
    ]
