# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-03-26 19:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metricsapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='elasticsearchsource',
            name='index',
            field=models.TextField(default=b'*', help_text='Elasticsearch index name. Can include wildcards (&quot;*&quot;) or date math expressions (&quot;&lt;static_name{date_math_expr{date_format|time_zone}}\\&gt;&quot;). For example, an index could be &quot;&lt;metrics-{now/d}&gt;,&lt;metrics-{now/d-1d}&gt;&quot;, resolving to &quot;metrics-yyyy-mm-dd,metrics-yyyy-mm-dd&quot;, for the past 2 days of metrics.', max_length=1000),
        ),
    ]
