# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-10-17 19:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metricsapp', '0002_auto_20190326_1901'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grafanapanel',
            name='dashboard_uri',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='grafanapanel',
            name='panel_url',
            field=models.CharField(max_length=2500, null=True),
        ),
    ]
